on:
 pull_request:
  types: [closed]
jobs:
  repo-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: git-sync
      uses: wei/git-sync@v3
      with:
        source_repo: $GITHUB_REPOSITORY
        source_branch: "main"
        destination_repo: ${{ secrets.glitch_git_URL }}
        destination_branch: "master"
